AliRaza011/Models/ErrorViewModel.cs
using System;

namespace AliRaza011.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AliRaza011/Models/ordermodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AliRaza011.Models
{
    public class ordermodel
    {
        [Key]
        public int id { get; set; }
        public string Name { get; set; }
        [Required]
        public int dis_quantity { get; set; }
        public int price { get; set; }

    }
}

AliRaza011/Controllers/HomeController.cs
using AliRaza011.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AliRaza011.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AliRaza011/Controllers/ordermodelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AliRaza011.Data;
using AliRaza011.Models;

namespace AliRaza011.Controllers
{
    public class ordermodelsController : Controller
    {
        private readonly storedbContext _context;

        public ordermodelsController(storedbContext context)
        {
            _context = context;
        }

        // GET: ordermodels
        public async Task<IActionResult> Index()
        {
            return View(await _context.ordermodel.ToListAsync());
        }

        // GET: ordermodels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordermodel = await _context.ordermodel
                .FirstOrDefaultAsync(m => m.id == id);
            if (ordermodel == null)
            {
                return NotFound();
            }

            ViewBag.Total = ordermodel.dis_quantity * ordermodel.price;
            return View(ordermodel);
        }

        // GET: ordermodels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ordermodels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,dis_quantity,price")] ordermodel ordermodel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ordermodel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ordermodel);
        }


      

        // GET: ordermodels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordermodel = await _context.ordermodel
                .FirstOrDefaultAsync(m => m.id == id);
            if (ordermodel == null)
            {
                return NotFound();
            }

            return View(ordermodel);
        }

        // POST: ordermodels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordermodel = await _context.ordermodel.FindAsync(id);
            _context.ordermodel.Remove(ordermodel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ordermodelExists(int id)
        {
            return _context.ordermodel.Any(e => e.id == id);
        }
    }
}

AliRaza011/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AliRaza011/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AliRaza011</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AliRaza011</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ordermodels" asp-action="Index">Store</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AliRaza011 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AliRaza011/Views/ordermodels/Create.cshtml
@model AliRaza011.Models.ordermodel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ordermodel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dis_quantity" class="control-label"></label>
                <input asp-for="dis_quantity" class="form-control" />
                <span asp-validation-for="dis_quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AliRaza011/Views/ordermodels/Delete.cshtml
@model AliRaza011.Models.ordermodel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ordermodel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dis_quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dis_quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AliRaza011/Views/ordermodels/Details.cshtml
@model AliRaza011.Models.ordermodel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ordermodel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dis_quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dis_quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class="col-sm-2">
            <span>Total Value</span>
        </dt>
        <dd class="col-sm-10">
            @ViewBag.total
        </dd>
    </dl>
</div>
<div>
 
    <a asp-action="Index">Back to List</a>
</div>

AliRaza011/Views/ordermodels/Index.cshtml
@model IEnumerable<AliRaza011.Models.ordermodel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dis_quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dis_quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
               
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>